[options]
admin_passwd = $pbkdf2-sha512$600000$cW7t/X9PCeG819r7H4OQcg$kwudJVvA4BGZZkYrZ9tccDLYCZ4oLFhnBvZ7z.qNXpGnTvA5zlbM3Kl5bz0oXKolWHX6TJ7dYkmaA403mX.xtg
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo-translate
list_db = False
log_level = info
proxy_mode = False
timezone = Asia/Shanghai
